import pymorphy3

_morph = pymorphy3.MorphAnalyzer()

# Russian (nominative singular) → English ingredient names
FOOD_RU_EN: dict[str, str] = {
    # Мясо и птица
    "курица": "chicken",
    "цыплёнок": "chicken",
    "индейка": "turkey",
    "свинина": "pork",
    "говядина": "beef",
    "баранина": "lamb",
    "телятина": "veal",
    "утка": "duck",
    "гусь": "goose",
    "кролик": "rabbit",
    "фарш": "ground meat",
    "бекон": "bacon",
    "ветчина": "ham",
    "колбаса": "sausage",
    "сосиска": "sausage",
    "карбонад": "pork loin",
    "грудка": "breast",
    "филе": "fillet",
    "окорочок": "chicken leg",
    "крылышко": "chicken wing",
    "шея": "neck",
    "рёбрышко": "ribs",
    "субпродукт": "offal",
    "печень": "liver",
    "сердце": "heart",
    "почка": "kidney",
    # Рыба и морепродукты
    "рыба": "fish",
    "лосось": "salmon",
    "сёмга": "salmon",
    "форель": "trout",
    "тунец": "tuna",
    "треска": "cod",
    "минтай": "pollock",
    "хек": "hake",
    "судак": "pike perch",
    "щука": "pike",
    "карп": "carp",
    "окунь": "perch",
    "сельдь": "herring",
    "скумбрия": "mackerel",
    "шпрот": "sprat",
    "сардина": "sardine",
    "анчоус": "anchovy",
    "креветка": "shrimp",
    "краб": "crab",
    "кальмар": "squid",
    "осьминог": "octopus",
    "мидия": "mussels",
    "устрица": "oyster",
    "гребешок": "scallop",
    "икра": "caviar",
    # Прилагательные формы (куриный, говяжий и тп)
    "куриный": "chicken",
    "говяжий": "beef",
    "свиной": "pork",
    "бараний": "lamb",
    "индюшиный": "turkey",
    "рыбный": "fish",
    "томатный": "tomato",
    "сливочный": "butter",
    "оливковый": "olive oil",
    "растительный": "vegetable oil",
    "подсолнечный": "sunflower oil",
    "кокосовый": "coconut",
    "грецкий": "walnut",
    "мускатный": "nutmeg",
    # Омонимы и сложные случаи
    "лука": "onion",
    # Овощи
    "картофель": "potato",
    "картошка": "potato",
    "морковь": "carrot",
    "лук": "onion",
    "чеснок": "garlic",
    "помидор": "tomato",
    "томат": "tomato",
    "огурец": "cucumber",
    "перец": "pepper",
    "капуста": "cabbage",
    "брокколи": "broccoli",
    "цветная капуста": "cauliflower",
    "брюссельская капуста": "brussels sprouts",
    "шпинат": "spinach",
    "салат": "lettuce",
    "свёкла": "beet",
    "редис": "radish",
    "редька": "radish",
    "тыква": "pumpkin",
    "кабачок": "zucchini",
    "баклажан": "eggplant",
    "авокадо": "avocado",
    "кукуруза": "corn",
    "горох": "peas",
    "фасоль": "beans",
    "чечевица": "lentils",
    "нут": "chickpeas",
    "спаржа": "asparagus",
    "артишок": "artichoke",
    "сельдерей": "celery",
    "порей": "leek",
    "пастернак": "parsnip",
    "топинамбур": "jerusalem artichoke",
    "ревень": "rhubarb",
    "зелень": "greens",
    "петрушка": "parsley",
    "укроп": "dill",
    "базилик": "basil",
    "кинза": "cilantro",
    "тимьян": "thyme",
    "розмарин": "rosemary",
    "орегано": "oregano",
    "мята": "mint",
    # Крупы и злаки
    "рис": "rice",
    "гречка": "buckwheat",
    "гречиха": "buckwheat",
    "овёс": "oats",
    "пшеница": "wheat",
    "ячмень": "barley",
    "просо": "millet",
    "кукурузная крупа": "cornmeal",
    "манка": "semolina",
    "булгур": "bulgur",
    "киноа": "quinoa",
    "кускус": "couscous",
    "перловка": "pearl barley",
    # Молочные продукты
    "молоко": "milk",
    "сливки": "cream",
    "масло": "butter",
    "сметана": "sour cream",
    "кефир": "kefir",
    "йогурт": "yogurt",
    "творог": "cottage cheese",
    "сыр": "cheese",
    "пармезан": "parmesan",
    "моцарелла": "mozzarella",
    "брынза": "feta",
    "рикотта": "ricotta",
    "яйцо": "egg",
    # Мучные изделия
    "мука": "flour",
    "хлеб": "bread",
    "булка": "bun",
    "батон": "loaf",
    "лаваш": "lavash",
    "макароны": "pasta",
    "спагетти": "spaghetti",
    "лапша": "noodles",
    "пельмени": "dumplings",
    "вареники": "vareniki",
    # Фрукты и ягоды
    "яблоко": "apple",
    "груша": "pear",
    "слива": "plum",
    "вишня": "cherry",
    "черешня": "sweet cherry",
    "абрикос": "apricot",
    "персик": "peach",
    "нектарин": "nectarine",
    "виноград": "grapes",
    "апельсин": "orange",
    "мандарин": "tangerine",
    "лимон": "lemon",
    "лайм": "lime",
    "грейпфрут": "grapefruit",
    "банан": "banana",
    "киви": "kiwi",
    "манго": "mango",
    "ананас": "pineapple",
    "папайя": "papaya",
    "гранат": "pomegranate",
    "клубника": "strawberry",
    "малина": "raspberry",
    "черника": "blueberry",
    "голубика": "blueberry",
    "смородина": "currant",
    "крыжовник": "gooseberry",
    "ежевика": "blackberry",
    "арбуз": "watermelon",
    "дыня": "melon",
    # Орехи и семена
    "орех": "nuts",
    "грецкий орех": "walnut",
    "миндаль": "almond",
    "фундук": "hazelnut",
    "кешью": "cashew",
    "фисташка": "pistachio",
    "арахис": "peanut",
    "семечка": "sunflower seeds",
    "тыквенное семя": "pumpkin seeds",
    "кунжут": "sesame",
    "мак": "poppy seeds",
    "лён": "flaxseed",
    # Приправы и соусы
    "соль": "salt",
    "сахар": "sugar",
    "мёд": "honey",
    "уксус": "vinegar",
    "соевый соус": "soy sauce",
    "горчица": "mustard",
    "майонез": "mayonnaise",
    "кетчуп": "ketchup",
    "томатная паста": "tomato paste",
    "аджика": "adjika",
    "хрен": "horseradish",
    "васаби": "wasabi",
    "корица": "cinnamon",
    "имбирь": "ginger",
    "куркума": "turmeric",
    "паприка": "paprika",
    "кумин": "cumin",
    "кориандр": "coriander",
    "кардамон": "cardamom",
    "гвоздика": "cloves",
    "мускатный орех": "nutmeg",
    "лавровый лист": "bay leaf",
    "перец чёрный": "black pepper",
    "перец красный": "red pepper",
    "шафран": "saffron",
    "ваниль": "vanilla",
    "какао": "cocoa",
    # Масла
    "растительное масло": "vegetable oil",
    "оливковое масло": "olive oil",
    "подсолнечное масло": "sunflower oil",
    "кокосовое масло": "coconut oil",
    # Грибы
    "гриб": "mushrooms",
    "шампиньон": "champignon",
    "белый гриб": "porcini",
    "лисичка": "chanterelle",
    "опята": "honey mushrooms",
    "вешенка": "oyster mushroom",
    "трюфель": "truffle",
    # Консервы и полуфабрикаты
    "тушёнка": "canned meat",
    "консерва": "canned food",
    "оливка": "olives",
    "маслина": "olives",
    "каперс": "capers",
    "анчоус": "anchovies",
    # Напитки и прочее
    "вино": "wine",
    "пиво": "beer",
    "коньяк": "cognac",
    "водка": "vodka",
    "бульон": "broth",
    "желатин": "gelatin",
    "дрожжи": "yeast",
    "разрыхлитель": "baking powder",
    "сода": "baking soda",
    "крахмал": "starch",
    "шоколад": "chocolate",
    "карамель": "caramel",
    "сироп": "syrup",
    "варенье": "jam",
    "джем": "jam",
}


def lemmatize(word: str) -> str:
    parsed = _morph.parse(word)
    if not parsed:
        return word
    return parsed[0].normal_form


def translate_ingredients(words: list[str]) -> list[str]:
    """Translate Russian ingredient words to English using lemmatization + dictionary."""
    result = []
    for word in words:
        lemma = lemmatize(word)
        en = FOOD_RU_EN.get(lemma)
        if en:
            result.append(en)
        else:
            result.append(word)
    return result
